version: "3"

services:
  lb:
    image: gerardomc/nginx_balancenode
    ports:
      - "80:80"
    command: [nginx-debug, "-g", "daemon off;"]
    volumes:
      - ./nginx-docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
  app1:
    image: gerardomc/balancenode
    ports:
      - "1000:1000"
    environment:
      - PORT=1000
      - SERVER_ID=1
      - MONGODB_CNN=mongodb+srv://admin:admin123@cluster0.aql5h.mongodb.net/bcc?retryWrites=true&w=majority
      - SECRETORPRIVATEKEY=J8PCyfC3hsRaFhbyrFY5kurYD30FWfmpHzke3aFM9hmaRKI6yfSzED+Z+8U+ols3LS2HwLPsSlnJw+j5LyX20r7ZR9N16XUkZbdfmTdfHb3STSADTeiuLxgq0AXkAfVTKgdG3PLf5JZuxqJMxYWKNdOFxXQeeBF71zeeIv5GTOo= 
      - OPENSSL_CONF=/tmp/openssl.cnf 
  app2:
    image: gerardomc/balancenode
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
      - SERVER_ID=2
      - MONGODB_CNN=mongodb+srv://admin:admin123@cluster0.aql5h.mongodb.net/bcc?retryWrites=true&w=majority
      - SECRETORPRIVATEKEY=J8PCyfC3hsRaFhbyrFY5kurYD30FWfmpHzke3aFM9hmaRKI6yfSzED+Z+8U+ols3LS2HwLPsSlnJw+j5LyX20r7ZR9N16XUkZbdfmTdfHb3STSADTeiuLxgq0AXkAfVTKgdG3PLf5JZuxqJMxYWKNdOFxXQeeBF71zeeIv5GTOo= 
      - OPENSSL_CONF=/tmp/openssl.cnf 
  app3:
    image: gerardomc/balancenode
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SERVER_ID=3
      - MONGODB_CNN=mongodb+srv://admin:admin123@cluster0.aql5h.mongodb.net/bcc?retryWrites=true&w=majority
      - SECRETORPRIVATEKEY=J8PCyfC3hsRaFhbyrFY5kurYD30FWfmpHzke3aFM9hmaRKI6yfSzED+Z+8U+ols3LS2HwLPsSlnJw+j5LyX20r7ZR9N16XUkZbdfmTdfHb3STSADTeiuLxgq0AXkAfVTKgdG3PLf5JZuxqJMxYWKNdOFxXQeeBF71zeeIv5GTOo=
      - OPENSSL_CONF=/tmp/openssl.cnf 